End of year 2022 post
ARCLeeds/arcleeds.github.io pull request #167
Opened 2022-12-15 12:30 UTC by Sparrow0hawk

This PR adds a blog post wrapping up stuff that happened in 2022.

Please add/adjust to include your own flourish!

2022-12-15 13:24 UTC, patricia-ternes requested changes
Amazing job @Sparrow0hawk 

I suggested two minor changes. But I am happy in approve this

2022-12-15 13:24 UTC, patricia-ternes commented on blog/_posts/2022-12-16-endofyear2022.md
> +This year we organised, with the help of a fabulous organising committee, the first ever [Research Computing Leeds Conference](https://rescompleedscon.github.io/conference2022/). This brought togethe
```suggestion
This year we organised, with the help of a fabulous organising committee, the first ever [Research Computing Leeds Conference](https://rescompleedscon.github.io/conference2022/). This brought together researchers from across the University who did computational research in some form and allowed them to tell their story and share best practices. It was held over 2 days with 2 streams of activity with an exciting range of talks, workshop session and panel discussions on Open Research and Sustainability and Research Computing.
```

2022-12-15 20:30 UTC, jhodrien approved these changes

2022-12-16 10:00 UTC, NGRhodes reviewed
Ignore

2022-12-16 10:10 UTC, patricia-ternes approved these changes

2022-12-16 10:22 UTC, NGRhodes commented on blog/_posts/2022-12-16-endofyear2022.md
> +If you'd like to explore getting RSE support for work you are doing or have planned why not [get in touch](https://it.leeds.ac.uk/it?id=sc_cat_item&sys_id=7587b2530f675f00a82247ece1050eda)?
```suggestion
RSE project work is already being scheduled for 2023, if you'd like to explore getting RSE support for work you are doing or have planned why not [get in touch](https://it.leeds.ac.uk/it?id=sc_cat_item&sys_id=7587b2530f675f00a82247ece1050eda)?
```

2022-12-16 10:22 UTC, NGRhodes commented on blog/_posts/2022-12-16-endofyear2022.md
> +Overall, we delivered approximately 30 courses to over 500 researchers on computational techniques and best practices. We'll be back with more sessions in 2023 and also have other new courses in deve
```suggestion
Overall, we delivered approximately 30 courses to over 500 researchers on computational techniques and best practices. We'll be back with more sessions in 2023 and have new courses and updates in development!
```

2022-12-16 15:47 UTC, merged