Platform update
ARCLeeds/arcleeds.github.io pull request #240
Opened 2024-09-27 15:48 UTC by patricia-ternes

This PR add to the Research Platforms page:

- Roadmap
- A more detailed list of resources

All the content was drafted in a meeting with @jhodrien;

It is the first draft of the content, as more and more details can be added, but I don't want to spend days going in one direction if it is not the right one.

The tables are in `html` because I want to include bullet points in the cells; the wordpress is in html as well, so I didn't bother to find a different solution.

2024-10-01 11:29 UTC, jhodrien requested changes
All in, I think this is much more useful to people than what we had before, and it feels easy to add to, or link other materials.  Thanks.  Suggested changes are very minor, please accept or ignore to taste.

If I was to suggest a future addition, I think it's some sort of computational consideration flowchart, so that a new PhD student can work through a set of questions as to what they're trying to do, and find the likely best platform to use.

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +   - For large, multi-node, or specialized GPU jobs, Tier-2 (Regional) and Tier-1 (National) HPC facilities offer matchless power and scale.
```suggestion
   - For large, multi-node, or specialized GPU jobs, Tier-2 (Regional) and Tier-1 (National) HPC facilities offer unmatched power and scale.
```

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +   - For large, multi-node, or specialized GPU jobs, Tier-2 (Regional) and Tier-1 (National) HPC facilities offer matchless power and scale.
Also, you put "Tier 3" higher up but "Tier-2" here.  Pick on or the other style.

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +        <li>Standard request/support via University IT - faster deliver/support</li>
```suggestion
        <li>Standard request via University IT - fast delivery/setup</li>
```

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +        <li>Standard request/support via University IT - faster deliver/support</li>
```suggestion
        <li>Standard request via University IT - fast delivery/setup</li>
```

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +        <li>Request/support via University IT</li>
```suggestion
        <li>Request via University IT</li>
```

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +        <li>Standard request/support via University IT - faster deliver/support</li>
I think stressing the support side here is potentially confusing, as these are supported by IT, but so is Windows Desktop, and various other bits too like the HPC.

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +        <li>Useful for trialing and debugging on a high end machine without needing to buy a workstation or queue on the HPC for testing</li>
```suggestion
        <li>Useful for trialling and debugging on a high end machine without needing to buy a workstation or queue on the HPC for testing</li>
```

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +        <li>Benefits of RAM/Cores/GPU, a general issue of scale compared to personal systems</li>
```suggestion
        <li>Benefits of higher specification RAM/cores/GPU; generally high end compared to personal systems</li>
```

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +      <td>Colab</td>
```suggestion
      <td>Google Colab</td>
```

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +      <td><a href="https://colab.research.google.com/" target="_blank">Colab Homepage</a></td>
```suggestion
      <td><a href="https://colab.research.google.com/" target="_blank">Google Colab Homepage</a></td>
```

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +      <td>Can install dependencies more nicely than Colab</td>
```suggestion
      <td>Easier to install dependencies than Colab</td>
```

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +        <li>Run actions in windows, linux and macos environments</li>
```suggestion
        <li>Run actions in Windows, Linux and macOS environments</li>
```

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +        <li>GPUs (V100), but a relatively small number</li>
```suggestion
        <li>GPUs (Nvidia Tesla V100), but a relatively small number</li>
```

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +      <td>11 times more flops than ARC3 and ARC4 combined</td>
```suggestion
      <td>11 times more FLOPS than ARC3 and ARC4 combined</td>
```

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +        <li>GPU, V100</li>
```suggestion
        <li>100% GPU, Nvidia Tesla V100</li>
```

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +† *The JADE2 account registration period closed on 01/09/2024. As of this date, we are no longer able to approve project requests. 6th January 2025: All access to the service will be withdrawn and ph
```suggestion
† *The JADE2 account registration period closed on 01/09/2024. As of this date, we are no longer able to approve project requests. 1st November 2024: Batch and interactive access to all compute resources will be withdrawn. 6th January 2025: All access to the service will be withdrawn and physical decommissioning of the system will commence.*
```

2024-10-01 11:29 UTC, jhodrien commented on pages/research_platforms.md
> +        <li>Jupyer notebook support</li>
```suggestion
        <li>Jupyter notebook support</li>
```

2024-10-04 10:18 UTC, patricia-ternes commented on pages/research_platforms.md
> +   - When your research requires heavy computation, high-end GPUs, or parallel processing, it’s time to consider our local (Tier 3) HPC resources like.
```suggestion
   - When your research requires heavy computation, high-end GPUs, or parallel processing, it’s time to consider our local (Tier 3) HPC resources.
```

2024-10-04 10:25 UTC, patricia-ternes commented on pages/research_platforms.md
> +   - When your research requires heavy computation, high-end GPUs, or parallel processing, it’s time to consider our local (Tier 3) HPC resources like.
No, I will include the options just in the table to not repeat to much information.

2024-10-04 10:26 UTC, patricia-ternes commented
@jhodrien everything updated, can you approve it if you are happy?

2024-10-04 10:26 UTC, jhodrien approved these changes

2024-10-04 10:31 UTC, merged